### ISSUE TITLE
Time Resolution

### ISSUE THREAD

**Issue by NMAC427** [koslo/node-red-contrib-time-controller#3]
The output value doesn't change smoothly. Instead it only changes once every minute, even if the refresh interval is set to one second. This is because on line 139 (`now.seconds(0).millisecond(0)`) and line 249 (`this.node.now = () => moment().seconds(0).millisecond(0)`) in the `TimeController.js` file.
By replacing the `.seconds(0).millisecond(0)` part on both of these lines, this issue can be fixed.

**Comment by koslo** [comment]
Hi. Yes, the timing with seconds was not really supported until now. I have added it...
